---
- name: create instance
  gcp_compute_instance:
   name: webserver01
   machine_type: e2-micro
   disks:
     - auto_delete: true
       boot: true
       initialize_params:
         source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2010-groovy-v20210511a
   network_interfaces:
     - access_configs:
         - name: External Nat
           type: ONE_TO_ONE_NAT         
   metadata:
     startup-script:  |
         #! /bin/bash
         apt -y update
         apt -y install httpd
         sudo echo "Salut Fred" > /var/www/html/index.html
         sudo systemctl restart httpd
   zone: europe-west6-a
   project: iaac-gloud-313808
   auth_kind: serviceaccount
   service_account_file: /home/frederic_pitteloud_gmail_com/security/ansible-iaac-gcloud.json
   state: present